# Generated by Django 5.2.4 on 2025-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_type', models.CharField(choices=[('users', '用户统计'), ('projects', '项目统计'), ('competitions', '比赛统计'), ('shares', '分享统计')], max_length=20, verbose_name='统计类型')),
                ('data', models.JSONField(verbose_name='统计数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '管理员统计',
                'verbose_name_plural': '管理员统计',
                'db_table': 'admin_stats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('project', '项目举报'), ('share', '分享举报'), ('user', '用户举报'), ('competition', '比赛举报')], max_length=20, verbose_name='举报类型')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('reason', models.TextField(verbose_name='举报原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已处理'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
