# Generated by Django 5.2.4 on 2025-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('announcement_type', models.CharField(choices=[('system', '系统公告'), ('competition', '比赛公告'), ('project', '项目公告')], default='system', max_length=20, verbose_name='公告类型')),
                ('is_important', models.BooleanField(default=False, verbose_name='是否重要')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='图片')),
                ('link', models.CharField(max_length=500, verbose_name='链接')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banners',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0, verbose_name='总用户数')),
                ('total_projects', models.IntegerField(default=0, verbose_name='总项目数')),
                ('total_competitions', models.IntegerField(default=0, verbose_name='总比赛数')),
                ('total_shares', models.IntegerField(default=0, verbose_name='总分享数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页统计',
                'verbose_name_plural': '首页统计',
                'db_table': 'home_stats',
            },
        ),
        migrations.CreateModel(
            name='HotTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '热门标签',
                'verbose_name_plural': '热门标签',
                'db_table': 'hot_tags',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='HotTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='话题标题')),
                ('tag', models.CharField(max_length=50, verbose_name='标签')),
                ('count', models.IntegerField(default=0, verbose_name='讨论次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '热门话题',
                'verbose_name_plural': '热门话题',
                'db_table': 'hot_topics',
                'ordering': ['-count'],
            },
        ),
    ]
