# Generated by Django 5.2.4 on 2025-07-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_banner_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotTag',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='HotTopic',
            new_name='Topic',
        ),
    ]
