# Generated by Django 5.2.4 on 2025-07-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='比赛标题')),
                ('description', models.TextField(verbose_name='比赛描述')),
                ('organizer', models.CharField(max_length=100, verbose_name='主办方')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='competitions/', verbose_name='海报')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'db_table': 'competitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
