# Generated by Django 5.2.4 on 2025-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='分享标题')),
                ('content', models.TextField(verbose_name='分享内容')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='技术栈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分享',
                'verbose_name_plural': '分享',
                'db_table': 'shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
